### ISSUE TITLE
Dashboard Pokémon total spawn/Lure graphs are not only 7 days

### ISSUE THREAD

**Issue by pki0** [brusselopole/Worldopole#100]
## Expected Behavior

+ Pokémon total spawn graph shows last 7 days
+ Lure graph the same
+ Read the times/dates on the X axis 
## Current Behavior

Pokémon total spawn graph shows all days and is slow as hell
## Possible Solution

+ For last 7 days:

In dashboard.graph.js.php:

Around line 50:

+ add $lastweek
+ add if condition for $lastweek

```
$now		 = time(); 
$yesterday	 = $now-86400; 
$lastweek        = $now-604800;
$i=0; 

foreach($stats as $data){
	
	if($data->timestamp > $lastweek){

	$labels_global[]	= '"'.date('d/m h:i a', $data->timestamp ).'"';
	$total[]                    = $data->pokemon_now;
    }
	
if($data->timestamp > $yesterday){
```
And for lure:

```
    if($data->timestamp > $lastweek){
	
		$labels_stops[]			= '"'.date('d/m - h:i a', $data->timestamp ).'"';
		$lure[]				= $data->lured; 
	
	}
```

+ For the axes:

Current solution is to add the date to the X axis by the following:
```

if($data->timestamp > $yesterday){
		
		$labels[] = '"'.date('d/m h:i a', $data->timestamp ).'"'; 
```

and:
```

if($data->timestamp > $yesterday){
	
		$labels_gym[]			= '"'.date('d/m h:i a', $data->timestamp ).'"';
```

![graph](https://cloud.githubusercontent.com/assets/21021281/20350151/fbe8f5ce-ac0d-11e6-92e3-2a575f239d88.PNG)
![prestige](https://cloud.githubusercontent.com/assets/21021281/20350172/1682f1f0-ac0e-11e6-80bd-6dc91e7b3ecc.PNG)

**Comment by SiteEffect** [comment]
Nice find and thanks!

**Comment by pki0** [comment]
Updated temp fix for axes

**Comment by Obihoernchen** [comment]
awesome man! :+1: 
I'll merge your changes soon.
Join our discord as well: https://discord.gg/SDvsxkN :)

**Comment by SiteEffect** [comment]
Change the timestamps to a clean appearance by deciding which localization we would like set as standard and after that change those `.date('d/m h:i a', $data->timestamp ).`. This should be unified because right now we have multiple approaches like 
- `d/m h:i a`
- `d.m - H:i`

I set mine all of mine format like to `d.m H:i` for date-time and `H:i`for time.

**Comment by Obihoernchen** [comment]
Closing this one. Continue in #104.
Thank you!
