### ISSUE TITLE
[Feature Request] Make most recents on "home.page.php" great again

### ISSUE THREAD

**Issue by Arengo** [brusselopole/Worldopole#101]
I question the use of the "home.page.php"'s most recent spawns in its current state. It's nice to see the scanner live but further the information provided for the user is pretty low.

## Expected Behavior

What someone likes to see there is on the one hand really rare spawns and how long ago this was. 

## Current Behavior

Shows rare spawns in the area with link to the Pokédex page. No further information is provided.

## Possible Solution

- [X] Change the Pokémon list to actually real mythic spawns, maybe change the general rare categories for all Pokémon that they reflect the actual rarity of Pokémon in-game or their usefulness. Like "Mythic" for the most powerful Pokémon as well as extreme hard to obtain.
- [x] Further, provide a time information below the most recent Pokémons like "< 1min ago", "10min ago"

**Comment by pki0** [comment]
Mythic is actually at 0.01% of the Pokemon. 

It's hard to fix it for everyone. Because I have 3.5 Million Pokemon in my database and my percentage is a lot lower.

I made these changes for myself:

```
    if($arrondis >= 1){

        $pokelist[$key]['status'] = 'Very common'; 

    }elseif($arrondis >= 0.25){

        $pokelist[$key]['status'] = 'Common';

    }elseif($arrondis >= 0.01){

        $pokelist[$key]['status'] = 'Rare';

    }elseif($arrondis >0 ){

        $pokelist[$key]['status'] = 'Mythic';

    }else{

        $pokelist[$key]['status'] = 'Unseen';

    }
```

The result:

![mythics](https://cloud.githubusercontent.com/assets/21021281/20351438/1a4f19bc-ac13-11e6-960c-69e0a62cd29f.PNG)

Maybe we can get some formula to calculate it better. :)

Or we can set it to: 
All Pokemon < 100 total spawn
All Pokemon with a spawrate < XXX

**Comment by Arengo** [comment]
Thanks for this nice approach. I think those numbers fit a lot better in general, however I just saw some flaws with this logic - am I right?

    `if($arrondis >= 1){

        $pokelist[$key]['status'] = 'Very common'; 

    }elseif($arrondis >= 0.25){

        $pokelist[$key]['status'] = 'Common';

    }elseif($arrondis >= 0.01){

        $pokelist[$key]['status'] = 'Rare';

    }elseif($arrondis >0 ){

        $pokelist[$key]['status'] = 'Mythic';

    }else{

        $pokelist[$key]['status'] = 'Unseen';

    }`

**Comment by Obihoernchen** [comment]
logic looks fine to me.
I'll test later today and probably change the thresholds a bit.

**Comment by Obihoernchen** [comment]
Rarity distribution should be way better now.
TODO: Show some more useful information

**Comment by SiteEffect** [comment]
Having a look into the time information right now

**Comment by Obihoernchen** [comment]
@Arengo did you make any progress on this?

**Comment by SiteEffect** [comment]
No, was busy with my map instead Worldopole. Sorry.

**Comment by SiteEffect** [comment]
PR inc. with time info

**Comment by Obihoernchen** [comment]
Closing this one because we have the PR now :+1: #122
