### ISSUE TITLE
Setup issues: /website.lock and /install/done.lock throw permission errors and REQUEST_SCHEME not avail

### ISSUE THREAD

**Issue by larsschwarz** [brusselopole/Worldopole#11]
Seems some files/dir require chmod before running?

Also seeing "undefined index: REQUEST_SCHEME in ... config.php on line 25" errors. Replacing it with http or https works of course, but there should be a fallback if that SERVER var is not avail on some installs.

**Comment by brusselopole** [comment]
Yes, /core/json/ needs to be readable and writable by apache user (www-data) to be able to update the rarety of 'mon

**Comment by larsschwarz** [comment]
How is /core/json dir related to /website.lock and /install/done.lock? So root dir needs to be writeable and /install, too?

**Comment by brusselopole** [comment]
The last commit update the system to need only read/write rights on /core/json/ and /install/  
Not the root directory 

( there's no link between /install/ and /core/json/, the first is only used once at install to check database status and rights on folders, the second to store json files )

**Comment by brusselopole** [comment]
( I thing we're fine about that w/ the last release so ... )
