### ISSUE TITLE
[Feature Request] Link Trainer Pokemon to Gym

### ISSUE THREAD

**Issue by bouelcom** [brusselopole/Worldopole#110]
Is it possible to link each of active pokemon of a Trainer directly to the respective Gym ?

**Comment by bouelcom** [comment]
Or linking all Gym that are affected by a trainer ? (Ex: if trainer have 3 pokemon in 3 different gym, it will show on the map where is their pokemon

**Comment by Obihoernchen** [comment]
Yes it's possible but we will not do this because someone could abuse this. This way you could snipe gyms of a specific trainer which is unfair.
We want to keep everything fair. 

Sorry.
