### ISSUE TITLE
Fix Mythic Only Pokemon

### ISSUE THREAD

**Issue by SkOODaT** [brusselopole/Worldopole#112]
Notice: Undefined property: stdClass::$rarity in C:\PokemonGO\PokemonGo-Site\PokemonGO\database\core\process\data.loader.php on line 538

Notice: Undefined property: stdClass::$rarity in C:\PokemonGO\PokemonGo-Site\PokemonGO\database\core\process\aru.php on line 148

**Comment by Obihoernchen** [comment]
@SkOODaT hmm using latest version? I don't get such a php notice. Do you use some custom `pokes.json`?

**Comment by SkOODaT** [comment]
yes latest version , 538 shows right at the top of the page ......it shows mythics but eventually they all just replaced by that error 148 (no custom pokes.json) 

Windows 7 ultimate
Xampp 3.2.2

its like it keeps looping in the array and just spits out errors after it lists all mythics

**Comment by Obihoernchen** [comment]
please test with newest update :)

**Comment by SkOODaT** [comment]
works great but you have 
pokes.json
```
    "128": {
      "atk": "148", 
      "candy_id": "128", 
      "charge_move": "Earthquake", 
      "def": "184", 
      "max_cp": "1845", 
      "max_pv": "130", 
      "quick_move": "Tackle", 
      "spawn_rate": 0,          <---------- This make it just show tauroses lol [0.3617?]
      "stam": "150", 
      "types": [
        "Normal"
      ]
    }, 
```
other regionals are 0 too i would say thier about as common as squrtles in respective areas 0.3617

**Comment by Obihoernchen** [comment]
You mean pokedex.json?
The `spawn_rate` field will be recalculated based on your spawns once a day.

Just wait a few hours or do: 
1. `touch -d "25 hours ago" pokedex.json`
2. reload page

**Comment by SkOODaT** [comment]
still learning not sure "touch -d "25 hours ago" pokedex.json" but yes i meant pokedex.json

**Comment by Obihoernchen** [comment]
Entering `touch -d "25 hours ago" core/json/pokedex.json` in your server command line will set the file modification time back 25 hours. So the server thinks it has to update the file ;)

Please report if your issue is fixed after your pokedex.json is up to date :+1:

**Comment by SkOODaT** [comment]
no wonder why i didnt understand ur talking linux lol i have my front web end map only being hosting on linux and im learning it but my main workers and the Worldopole site is being hosting off a windows machine :) i just changed thier rairity from unseen and its good
