### ISSUE TITLE
Update pokedex.json

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#115]
Update `core/json/pokedex.json` with:
- [x] Update best movesets (#239)
- [x] Add Gen2
- [X] New CP, HP, att, def, sta (Done: 75bd797)
- [x] Update Gen2 candy_ids, review Gen1 candy_ids (#239)

If anybody wants to help here feel free to do so :heart:

**Comment by Obihoernchen** [comment]
JSON file you can use and transfer in our `pokedex.json` format:
https://gist.github.com/Obihoernchen/2f518d67236153b50230e1fe03fdc87f

**Comment by SiteEffect** [comment]
We should consider to add Generation 2 slowly and give Baby Pokémon a different pokemon.page.php since they can't be found wild.

**Comment by Obihoernchen** [comment]
mhh I don't know I think we should just include them once gen 2 is finally released.
Right now I see no reason to include these pokemons because they will be unseen anyways.
Btw: https://pokemonkiel.de/pokemon implemented gen 2 already.

**Comment by PoUpA** [comment]
Gen 2 will be unseen on map but the are usefull for trainers page and for gyms.

**Comment by SiteEffect** [comment]
@PoUpA this is current state of Gen2 though. When it is finally launched PokemonGo-Map will quickly adapt I guess and show them on the Map. However, we might include babies for Pokédex and Trainers now and already be prepared for the future.

What happens in PokemonGo-Map when a Baby is found in a Gym? Correct data retrieved?

**Comment by SiteEffect** [comment]
@Obihoernchen nice! What are the sources?

**Comment by PoUpA** [comment]
great trainers page works now thanks

**Comment by Obihoernchen** [comment]
Gen2 incoming!
