### ISSUE TITLE
Does not work in subfolder

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#12]
The site doesn't work if you put it in a subfolder and DocumentRoot doesn't point to this subfolder, because all links are absolute paths to DocumentRoot.

So something like this doesn't work out of the box:

```
DocumentRoot /srv/www/vhosts/domain.com/htdocs/
https://domain.com/wordpress --> /srv/www/vhosts/domain.com/htdocs/wordpress
https://domain.com/worldopole --> /srv/www/vhosts/domain.com/htdocs/worldopole
```

This would result in 404 for image and css files like --> https://domain.com/core/pokemons/96.png
Shoulde be: https://domain.com/worldopole/core/pokemons/96.png

What do you think about it?
Use relative paths or add another config parameter site-url or something like this?
Or add some additional htaccess options?

**Comment by brusselopole** [comment]
This is probably due to the baseurl sents in headers. 
I'll check that this afternoon. 

Thanks for reporting !

**Comment by jasonhemu** [comment]
Same issue here.

**Comment by brusselopole** [comment]
@jasonhemu @Obihoernchen last commit is for you guys ;)

**Comment by Obihoernchen** [comment]
Thank you :)
Unfortunately this commit doesn't fix the problem. There are a few issues left.
I'll make some comments to commit 24d83e0b6b92f42611be8c288101659901e55550

**Comment by jasonhemu** [comment]
It's working now! Thanks all!

**Comment by Obihoernchen** [comment]
I've made some more fixes: https://github.com/Obihoernchen/Worldopole/commit/9b6da83c028025bfe4bf2d03f45057a1eb2b9eb8

On top of that you have to edit the .htaccess file:
- edit RewriteBase = name of your subfolder
- remove the leading '/' from all RewriteRules

Ex: `RewriteBase /pokemon/` and `RewriteRule ^pokemon/(.+)$                              index.php?page=pokemon&id=$1 ...`

I'm working on another commit.

**Comment by ghost** [comment]
Hi,
I have kind of the same problem. Some global variables aren't returning the proper value (I guess ?) for example in core/process/data.loader.php the path in $variables returns /var/www/html/Worldopole/core/process/../json/variables.json
I'm in the same situation as jasonhemu regarding links (you can check it here : http://jinck.ddns.net/Wordopole/ )

Note : I'm using a Linux system and trying to work with a subfolder.

By the way, love your website.
Thanks for the feedback :)

**Comment by Obihoernchen** [comment]
Next one: https://github.com/Obihoernchen/Worldopole/commit/f96545dc238be90fe9d8b4d95f1059ad1ce1ad11

**Comment by brusselopole** [comment]
Guys, would you check the latest master if it works on your subfolder? 
I did forget to push the new config.example.php 

@Obihoernchen I thing (really only thing) that I may have found the solution without need to add the subfolder in the htaccess.

**Comment by jasonhemu** [comment]
All pages are working now. Thanks much!

**Comment by brusselopole** [comment]
omg, thanks you for debugging! (and challenge ✌️ )

**Comment by Obihoernchen** [comment]
Fixed 👍  1000thx
