### ISSUE TITLE
[Issue] Sorting Pokémon by disappear_time is not appropriate anymore

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#123]
## Expected Behavior
When sorting for the newest Pokémon, we want to see the newest, not those with the most time left.

## Current Behavior

When listing Pokémon we just found, we want to sort for the newest not those which are active the longest time. Once, all Pokémon where assigned a 15min disappear_time-interval by PokémonGo-Map when found. Today, we have Pokémon found with different time-patterns which result in different disappear_time-intervals and thereby Worldopole shows Pokémon which are like 10 min. old with still 6 min. on clock as newer than a just spawned and found 15 min. interval Pokémon. Hence, we should consider sorting in the right way considering further data base times like last_modified to prioritize for the real new Pokémon.

## Possible Solution

Take last_modified into account and think about a solution around different scan-schemes resulting in multiple scans of the same Pokémon

## Steps to Reproduce (for bugs)

1. Look your most recent which are just a time sorted list by disappear_time and not "most recent"

## Context

People like to see when they have to hurry and don't want to miss another rare because of this bug especially on main.page. For Pokédex it's not as crucial but correct data shown would be a viable idea.

**Comment by SiteEffect** [comment]
PUSH for attention because my brain is to laggy for this fix.

**Comment by Obihoernchen** [comment]
mhh that's really tricky... I reckon last_modified gets updated everytime a scanner sees a pokemon (again)?
Can you confirm this please?

**Comment by SiteEffect** [comment]
Confirmed, each re-scan changes ``last_modified`` to the current UTC time. This happens often in Hex-Scans but seldom for ``-ss`` or the new Speed-Scan.
