### ISSUE TITLE
Gym level calculation

### ISSUE THREAD

**Issue by kiralydavid** [brusselopole/Worldopole#13]
`Level : '.substr($data->gym_points,0,1).'`

I'm pretty sure that gym level isn't calculated this way :D Now it shows gyms with 10k+ prestige as lvl 1.

**Comment by brusselopole** [comment]
Many thanks for the PR 
Merged @ https://github.com/brusselopole/Worldopole/commit/9f1bfb8607eb645579c3584a027b43a9a9cee496
