### ISSUE TITLE
Reditect with Warning: Cannot modify header (solution)

### ISSUE THREAD

**Issue by titanicboyke** [brusselopole/Worldopole#130]
If there are people (like me) whose database is temporarily offline and not be redirected to offline.html but get errors like:
Warning: Cannot modify header information - headers already.......
put in the .htaccess

`php_value output_handler mb_output_handler`

I've tested it on my page

Regards,
Titanicboyke

**Comment by Obihoernchen** [comment]
Mhh I don't get such an error.
Maybe it's a problem with your default php.ini?

**Anybody else with the same problem?**

**Comment by SiteEffect** [comment]
Never had this error.
