### ISSUE TITLE
README.MD labels bugged

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#135]
Scrutinizer build status and general badge is transparent

**Screenshot**

<img width="425" alt="bildschirmfoto 2017-01-08 um 12 19 25" src="https://cloud.githubusercontent.com/assets/22680515/21749334/3822069e-d59d-11e6-9fc0-50acf25cb94f.png">

**Comment by Obihoernchen** [comment]
:-O
Can't reproduce this.
Which browser do you use?

Did you try to clear cache etc?

**Comment by PoUpA** [comment]
Can't reproduce this either

**Comment by SiteEffect** [comment]
It's fine again. Maybe it was temporary? I am using Chrome on Mac.
I think you can close it.
