### ISSUE TITLE
File extension (still) missing in single Pokemon page

### ISSUE THREAD

**Issue by kiralydavid** [brusselopole/Worldopole#15]
The src of the images of related pokemons are missing the .png extension

**Comment by Zegorax** [comment]
Simply edit pokemon.page.php, and add .png 

```
<a href="/pokemon/<?= $related_mon ?>">
                    <img src="/core/pokemons/<?= $related_mon ?>.png" alt="<?= $pokemons->$related_mon->name ?>.png" class="ing-responsive">
                </a>
```

**Comment by kiralydavid** [comment]
Yup, I already created a PR with it.

**Comment by brusselopole** [comment]
Hi! 
Thanks! 
This was corrected by @kiralydavid and just merged :-) 

Commit https://github.com/brusselopole/Worldopole/commit/5639930f405e3a9027e266b0f3f96dd4ff770e09
