### ISSUE TITLE
Current gym's level on gym page is not readable

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#153]
When looking up a specific gym in the map of gym.page one can not read all gym's current level due to lack of text contrast. This is observable when the current level is not prestiged, meaning the gym just got this level and the bar did not move beyond the text-area of the level's bar part. There are some flaws with different team colours so we need a more difficult general solution than just setting it green for the current level or something.

## Expected Behavior

The user can retrieve the current gym level and distinguish between levels without the need of glasses, monocles, magnifiers or telescopes. This happens regardless of the gym's current team colour.

## Current Behavior (Screenshots)

Yup, it's level 10 for anyone who wonders.
<img width="241" alt="bildschirmfoto 2017-01-16 um 16 44 31" src="https://cloud.githubusercontent.com/assets/22680515/21989592/cb4b3e8a-dc0b-11e6-833d-6082277b4229.png">

And this one is something between 6 and 8, who knows what exactly...
<img width="239" alt="bildschirmfoto 2017-01-16 um 16 50 04" src="https://cloud.githubusercontent.com/assets/22680515/21989618/e5b7a4b6-dc0b-11e6-9112-70d5681fd6f1.png">

## Possible Solution

Find a good colour for all teams or specify it for each team and apply it to current level using for example php if conditions with a query for current gym level and/or team colour.

Take care that it's still readable for bars which are already prestiged inside it's current level like this gym
<img width="237" alt="bildschirmfoto 2017-01-16 um 16 54 58" src="https://cloud.githubusercontent.com/assets/22680515/21989785/8cef0206-dc0c-11e6-819c-ba325c3b47d9.png">

## Steps to Reproduce

1. Watch your website
2. Enjoy the awesome Worldopole, besides this inconvenience

**Comment by Obihoernchen** [comment]
Ouh please have a look at the latest codebase. Mastermind @PoUpA :nerd_face: did some changes in his last refactor commit: see https://obihoernchen.net/pokemon/gym for instance.

**Comment by PoUpA** [comment]
You're right, there is a bug for active behaviour ( your example for level
7 gym) and there is also a poor choice of colors :P I would switch to
lightgrey when inactive and black for actives (switching the thing a bit
... active is what matter so black will make it more clear)
