### ISSUE TITLE
pokewatch file missing

### ISSUE THREAD

**Issue by humer2000** [brusselopole/Worldopole#154]
the pokewatch php file is missing and cannot be located in pages folder.
where is this file ?

**Comment by pki0** [comment]
Did you add this page by yourself?

**Comment by humer2000** [comment]
no, it's included in the header
![untitled](https://cloud.githubusercontent.com/assets/24587932/22159071/9b3e570e-df3f-11e6-8fea-ff07b2a74449.png)

**Comment by pki0** [comment]
Hmm, I can't find it in the source code.
Are you sure that you haven't created this one by yourself?

Do you have a 'fresh' pull from the repo?

Please have look inside your /core/json/variables.json and find "PokeWatch" and paste the part here.

**Comment by humer2000** [comment]
{ "type" : "link", "href" : "pokewatch", "text" : "PokeWatch", "icon" : "fa-search-plus" }

btw, i downloaded the file here, yesterday. i guess it's an up2date version

**Comment by humer2000** [comment]
i have also another problem, the file home.script.js renames itself home.script.1488955552.js or another number. why ?

**Comment by Obihoernchen** [comment]
There is no (and never was) a pokewatch site or entry in variables.json. This have to be your own edit. 
The js file gets renamed to fix caching issues. The number is the last modified Unix timestamp of the file. You have to copy the htaccess file to .htaccess to resolve this back to the original file (see install instructions).
