### ISSUE TITLE
map heat vs plot

### ISSUE THREAD

**Issue by humer2000** [brusselopole/Worldopole#156]
Hi folks

Actually when you click on a pokemon / map / you see the map with top heat areas (blue to red)

Is there any way to display pokemon plots instead of heats, with Lng/Lat, IV,... ?

thx
mike

**Comment by pki0** [comment]
Hi Mike,

yes it is possible. Look at google maps API v3 and inside the pokemon.maps.js.php file.

Here is the instruction: https://developers.google.com/maps/documentation/javascript/examples/icon-simple

You have to read and understand the googleMaps API before I can help you.

Live-Demo:
https://pokemonkiel.de/pokemon/1

**Comment by humer2000** [comment]
thx @klatterhans 
Am newbie to this, do u have telegram so that i show you what am doing and what i need exacty ? this if you have few time to help me.
thx

**Comment by Obihoernchen** [comment]
@humer2000 please join our discord to talk with us: https://discord.gg/SDvsxkN :)
