### ISSUE TITLE
"Last spawns" string should be changed to "Last mythic spawns" if "mythic_recents" is enabled

### ISSUE THREAD

**Issue by z0n** [brusselopole/Worldopole#171]
## Expected Behavior
I enabled the "mythic_recents" option in the variables.json, this should change the string "RECENT_SPAWNS" to something like "The most recent mythic spawns" to emphasize that only mythic spawns are displayed here.

## Current Behavior
"The most recent spawns" is displayed regardless of the "mythic_recents" option.

## Possible Solution
Change the string "RECENT_SPAWNS" to something like "The most recent mythic spawns"

## Context
It's not clear what kind of Pokémon are displayed in the recent spawns list.

**Comment by Obihoernchen** [comment]
#172 merged
