### ISSUE TITLE
	 Fatal error: Uncaught exception 'Exception' with message 'Timestamp is in the future'

### ISSUE THREAD

**Issue by Maveryy** [brusselopole/Worldopole#19]
I'm getting this error in the "When was it last seen?" section of any pokemon page

`Fatal error: Uncaught exception 'Exception' with message 'Timestamp is in the future' in /home/pokenata/public_html/functions.php:38 Stack trace: #0 /home/pokenata/public_html/pages/pokemon.page.php(101): time_ago(1472448094) #1 /home/pokenata/public_html/index.php(100): include('/home/pokenata/...') #2 {main} thrown in /home/pokenata/public_html/functions.php on line 38`

**Comment by brusselopole** [comment]
Hi, 
what's your server timezone?

**Comment by brusselopole** [comment]
This issue may have been corrected with time-management in release https://github.com/brusselopole/Worldopole/commit/f01a6b7a8c5a9741b8cd3b369293ea5aac7756a7 Let us know if you've still issue

**Comment by Maveryy** [comment]
It's working now. Thanks for the quick fix :)
