### ISSUE TITLE
Recents IV bar for Pokémon with unavailable IVs should look similar to the IV bar for Pokémon with available IVs

### ISSUE THREAD

**Issue by z0n** [brusselopole/Worldopole#190]
## Expected Behavior
The recents IV bar for Pokémon with no available IVs should look similar to the bar for Pokémon with available IVs.

## Current Behavior
This: ![image](https://cloud.githubusercontent.com/assets/7430908/22905392/5e042904-f240-11e6-83fe-8ab5017769fe.png)

## Possible Solution
This: ![image](https://cloud.githubusercontent.com/assets/7430908/22905373/504c62d6-f240-11e6-89fe-9b6e06f85e41.png)

## Context
It looks a little weird if the small IV bar pops up between the larger ones :)

**Comment by klatterhans** [comment]
I'l fix it later, thanks

**Comment by pki0** [comment]
@z0n Can you please test: #191 and tell me if it works
