### ISSUE TITLE
Rename /core/pokemonS/ to /core/pokemon/

### ISSUE THREAD

**Issue by larsschwarz** [brusselopole/Worldopole#2]
https://www.reddit.com/r/pokemongo/comments/4u2ikr/the_plural_of_pok%C3%A9mon_is_pok%C3%A9mon/ ;)

**Comment by waryas** [comment]
there's always someone to ruin the fun

**Comment by larsschwarz** [comment]
Come on, just tried to make a somewhat funny first issue - that's why I added the ;) to it

**Comment by brusselopole** [comment]
You're totally right! 
Our dev will be lashed for that horrible mistake! ;)
