### ISSUE TITLE
Corrupted links and "0 Pokémons / 0 Gyms / 0 Lures"

### ISSUE THREAD

**Issue by ftencaten** [brusselopole/Worldopole#21]
I followed all the install recommendations but when I tried to open the page it just show some links (all corrupted) and "0 Pokémons / 0 Gyms / 0 Lures". Checking the error.log of apache I have this message:

"[Sun Aug 28 19:38:38.564788 2016] [:error] [pid 6117] [client 127.0.0.1:57712] PHP Notice: Undefined variable: pokemon in /var/www/html/Worldopole/pages/home.page.php on line 49 [Sun Aug 28 19:38:38.564949 2016] [:error] [pid 6117] [client 127.0.0.1:57712] PHP Notice: Undefined variable: pokemon in /var/www/html/Worldopole/pages/home.page.php on line 51 [Sun Aug 28 19:38:38.564989 2016] [:error] [pid 6117] [client 127.0.0.1:57712] PHP Notice: Undefined variable: pokemon in /var/www/html/Worldopole/pages/home.page.php on line 51 [Sun Aug 28 19:38:38.565780 2016] [:error] [pid 6117] [client 127.0.0.1:57712] PHP Notice: Undefined variable: pokemon in /var/www/html/Worldopole/pages/home.page.php on line 51 [Sun Aug 28 19:38:38.565845 2016] [:error] [pid 6117] [client 127.0.0.1:57712] PHP Fatal error: Cannot access empty property in /var/www/html/Worldopole/pages/home.page.php on line 51"

Could be a error related to PHP and mysql connection?

**Comment by brusselopole** [comment]
Hi, 

the last time we got this issue it was due to some <?php tag 
Have you downloaded the latest version (or at least a version after commit https://github.com/brusselopole/Worldopole/commit/6e8d2e7f7d4de2401efe4e827c53231d67d8e709  )  ?

**Comment by ftencaten** [comment]
I tried again with the latest version (f01a6b7). Now it's presenting a different error message:

Fatal error: Call to a member function fetch_object() on a non-object in /var/www/html/Worldopole-master/core/process/data.loader.php on line 490

**Comment by brusselopole** [comment]
Just change your time_inverval to + or - X  from GMT time 
eg : for brussels setting is : `"time_inverval" : "+2"`

**Comment by ftencaten** [comment]
Oh, sorry, I forgot to do it. But now it returned to the previous error. The difference is that is now showing "The most recent spawns" and the list is updated when I refresh the page.

**Comment by brusselopole** [comment]
It returns `Undefined variable: pokemon in /var/www/html/Worldopole/pages/home.page.php` ?

**Comment by ftencaten** [comment]
No, changed to:

[Mon Aug 29 20:54:35.936114 2016] [mpm_prefork:notice] [pid 29897] AH00169: caught SIGTERM, shutting down
[Mon Aug 29 20:54:36.972562 2016] [mpm_prefork:notice] [pid 1435] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 configured -- resuming normal operations
[Mon Aug 29 20:54:36.972787 2016] [core:notice] [pid 1435] AH00094: Command line: '/usr/sbin/apache2'

**Comment by brusselopole** [comment]
Well, that's an Apache2 restart or gracefull log ^^ 
Nothing to do with our app :-)
