### ISSUE TITLE
[Feature Request] Count of Pokémon in intervals over continuous time

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#210]
## Requested Feature

We already have a time graph depending on day time to watch day/night spawns but we do not analyze a possible rotation of spawns or events taking place. Like the Party Pikachu event for Pokémon Day, referred to in belows awesome drawing

<img width="591" alt="bildschirmfoto 2017-03-07 um 11 59 12" src="https://cloud.githubusercontent.com/assets/22680515/23653988/f1920232-032e-11e7-8046-5db396456668.png">

*not for sale*

## Possible Solution

Query like
``SELECT disappear_time FROM pokemon WHERE pokemon_id = POKEMON_ID order by disappear_time INTERVAL UTC_NOW() - 1 DAY``
Graphs like those in Dashboard, maybe with a slider to cover a bigger timespan and an option for different time intervals i. e. day, month?!

## Your environment

I like MS Paint style. 
*ok, 1 Million DogeCoins*

**Comment by Obihoernchen** [comment]
Even though I really like the painting the queries for this to work would be too heavy :(
Maybe we come up with some awesome optimization in the future but for now I'll close this.
