### ISSUE TITLE
[Feature Request] Identifying biomes by assigning top 3 found non-common or nesting Pokémon in area grid

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#211]
This feature request tries to model a possible method to identify biomes and nests in scanned areas.

## Current Behavior

When we would like to identify a nest or biome we have to look through any Pokémon of interest, resulting in a huge time consumption which increases with additional generations.

## Expected Behavior

Hereby, I state, independently, that we should think of implementing a method to identify which biomes and which nests are in our scanned area by applying a grid to our covered area and query the database to pop out the top 3 Pokémon for each cell which are not ultra commons, but also nesting Pokémon. Hereby we could identify biomes on one map instead of comparing multiple Pokédex pages like Clefairy, Geodude etc. with each other. We might re-use the all new Pokédex map feature by altering it and migrating it to a standalone page domain.xyz/biomes and providing this feature over there. Doing ajax loading of queries for the watched area, limiting the total area possible to query to a geofence of our max. lat/long Pokémon in the database. A additional filter, like the moving bar should be used to limit db queries to a defined time window, like since last nest migration. Biomes are more static though and could be looked up and made them clearer to identify by expanding the displayed time window.

Additional, we should add ultra common rarity tag for pidgey, rattata & co. to faster sort them out instead extra querying the database, since very common can not be used because we would exclude important biome Pokémons with them.

**Comment by pki0** [comment]
This area-calculation could be a very high-CPU thing. And some nest are very small e.g. in bigger cities.
 
What about going another way?
Check every spawnpoint spawns in the last 24 hours:

Spawnpoint aaa = [1, 16, 1, 19, 1, 20, 1, ...]

The uncommon Bulbasaur is now identifying a single nest-spawnpoint.

So aaa = [1] and maybe neighbour spawnpoint aab = [1] too.

On Bulbasaur page you can show lat,lon of aaa, aab or on a spawnpoint map whatever.

Or for biomes:
Go by type:
aaa = [1 -> grass], aab = [1 -> grass].
Show on grass: aa, aab

Calculation could be done every two weeks or once a day?
I don't know how much time this need if you have a lot of spawnpoints

Overall: It's a filtered version of the typemaps I had some time ago. I like the idea, but define areas would be very hard.

**Comment by SiteEffect** [comment]
Biomes should not be identified by type - e. g. Dratinit/Dragonair are water biome, Dragonite is mountain biome. But I like your approach for the nest identification. And yes, this could be quite CPU intensive. In general going through spawnpoints and then comparing them is the better solution than making queries on individual areas.

**Comment by pki0** [comment]
This could work for nest identification via spawnpoints:

`SELECT pokemon.spawnpoint_id, pokemon.pokemon_id, count(pokemon.pokemon_id) as total_pokemon, pokemon.latitude, pokemon.longitude FROM pokemon INNER JOIN spawnpoint ON (spawnpoint.id = pokemon.spawnpoint_id) WHERE pokemon.disappear_time > UTC_TIMESTAMP - INTERVAL 24 HOUR AND pokemon.pokemon_id NOT IN('10','13','16','19','21','41','46','48','161','163','165','167') GROUP BY pokemon.spawnpoint_id, pokemon.pokemon_id HAVING total_pokemon > 8 ORDER BY pokemon.pokemon_id`


This should show all lat, lon for spawnpoints spawning more then 8 (1/3) times the same Pokemon in the last 24h. And exclude Pidgey, Rattata & other ultra commons.

For > 30.000 spawnpoints this query took 3 sec.

I get this result:
![bildschirmfoto 2017-03-13 um 18 26 03](https://cloud.githubusercontent.com/assets/21021281/23866921/95924b22-081a-11e7-8c74-a5452f2fb93f.png)


**Next steps for me:**
- Try to display them on a map 
- Check if all known nests are detected 
- Maybe scale the having operator a bit if not all / too many nests are found
- Use a for-loop and subtract the coordinates. If diff < 0.01 display only one of the spawnpoints to reduce count of Pokemon-images on the map

Maybe our JS master @PoUpA has a bit time trying to make a map out of this query ;-)

**Comment by SiteEffect** [comment]
I think the exclude list could be a bit more condensed in that query? Also maybe use include all known nest Pokémon instead of excluding others?

**Comment by pki0** [comment]
^ I made an edit and compressed the query a bit.
If you have a list which Pokemon can be in a nest feel free to send it to me.
I excluded only the ultra-commons

**Comment by Obihoernchen** [comment]
Implemented with #221
