### ISSUE TITLE
Gym details in map for not encountered gyms

### ISSUE THREAD

**Issue by friscoMad** [brusselopole/Worldopole#219]
## Expected Behavior
Show gym info inside the map with all the possible info.

## Current Behavior
If you try to open a gym that it is outside your area but that can be seen from your area, the worker does not encounter it, it does not have an image nor the full list or pokemons (maybe this is a problem of Pokemap).
Anyway this leads to gym details not being shown correctly, as the default UI is broken and only the extended UI with all the information is shown correctly.
![2017-03-17 14_12_36-pokemad _ sigue la conquista](https://cloud.githubusercontent.com/assets/487098/24044514/dc79158a-0b1b-11e7-971b-e3f9fdc228a6.png)
In fact the request leads to an exception in the response processing as gymInfos is null in 
```
function setGymDetails(gym)
{
	// replace http with https to fix mixed content
	var imgurl = gym.gymDetails.gymInfos.url;
```

## Possible Solution
At least Fix the style of the default UI (the one sent by core/process/aru.php with type "gym_map" and handle error in response.
Optimally change the default UI to be similar to the details UI (maybe with a generic image).

## Steps to Reproduce (for bugs)
1. Go to /gym 
2. Click in a gym that is outside the scan area

## Your Environment

* Version used: Latest version  60f6691
* URL: http://map.neose.es/gym
* Operating System and version (desktop or mobile): W7 Firefox 51

**Comment by pki0** [comment]
Hmm, I ask myself why you have gyms without details?

**Comment by SiteEffect** [comment]
I do have them, too. At the corners they get mapped but encountering gym-info does not work on them.

**Comment by friscoMad** [comment]
Not sure, it only happens with gyms outside the scan area but that can be seen from within the scan area, so probably a bug in the scanner code.
Anyway this should be improved as the extended detail request can fail and the regular display at least need somes style fixes.

**Comment by PoUpA** [comment]
Yep I know that, sorry didn't fixed it, iif the gym was scanned without
details it appear but fail to load the pokemons and the ui is screwed up
because ui is not set to display it. we need to do something when only the
gym defender pokemon id is known
