### ISSUE TITLE
No Pokestop found is your database

### ISSUE THREAD

**Issue by urinella** [brusselopole/Worldopole#22]
I'm using mariadb and the database is connected. Pokestops and even gyms are enabled on the PokemonGo-Map. But it shows: 

"No Pokestop found is your database"

Thanks

**Comment by brusselopole** [comment]
Hi, 
the website in only compatible with MySQL Database. 

Sorry.

**Comment by urinella** [comment]
Okay, but now it works fine with MariaDB!

I had a Lock-File in my install folder, just deleted it and now its working.
Just for Information ;-)

**Comment by brusselopole** [comment]
Wokay ... ^^ 
( the lock was due to a non-result from a request )
