### ISSUE TITLE
Monocle support

### ISSUE THREAD

**Issue by venimo** [brusselopole/Worldopole#225]
Please make it also possible for Monocle users.

I think it's mostly changes in the database stuff.

**Comment by ARGG1** [comment]
Hello, really will like this functionality. More and more people are coverting from RM to Monocle and want to keep this running. Please and thank you

**Comment by mimikq** [comment]
i'm trying my self edit that all DB stuff related to Worldopole and monocle. but i will maybe need som help by DEV guys i can provide DB or something ... I'm trying to change all the code for monocle DB, but for me it takes a time because me not familiar with db related stuff so if someone can help me or us or community i will appraise it

**Comment by PoUpA** [comment]
I just switched to monocle and will try to do something.

**Comment by mimikq** [comment]
is here anyone how can help me to fill to correct way of the php mysql scripts in file core/process/data.loader.php ?

```
mysql> SHOW TABLES;
+-------------------+
| Tables_in_monocle |
+-------------------+
| fort_sightings    |
| forts             |
| mystery_sightings |
| pokestops         |
| sightings         |
| spawnpoints       |
+-------------------+
6 rows in set (0.00 sec)
```

monocle have diff DB structure them RM. i tried myself to edit DBnames and etc and still no pokemon DB and etc error :(

**Comment by Obihoernchen** [comment]
You have to rewrite all queries... 
Wait for @PoUpA

**Comment by antonio9213** [comment]
What is the current status of this? Was Monocle support finally discarded?

**Comment by 123FLO321** [comment]
Working on it.
Will release a first "Beta-PR" soon.

**Comment by Obihoernchen** [comment]
Finally, we have a PR: https://github.com/brusselopole/Worldopole/pull/353
Discussion can continue there please :+1:
