### ISSUE TITLE
Added systemd timer instructions to the "Add-Dashboard-page-to-your-site" page

### ISSUE THREAD

**Issue by z0n** [brusselopole/Worldopole#228]
I don't know where to put this as the wiki doesn't allow pull requests. I added instructions for using systemd timers to update the dashboard and included some minor text fixes:

[Add-Dashboard-page-to-your-site.txt](https://github.com/brusselopole/Worldopole/files/886382/Add-Dashboard-page-to-your-site.txt)

**Comment by Obihoernchen** [comment]
I'll add it soon. Thank you!

**Comment by Obihoernchen** [comment]
Everybody should be able to edit the wiki now. Please test @z0n  👍

**Comment by z0n** [comment]
Done and added to the wiki. :)
