### ISSUE TITLE
Change top icon to a tri-color icon (For total gyms)

### ISSUE THREAD

**Issue by Zegorax** [brusselopole/Worldopole#23]
In the home section, the gyms that are not part of any teams is wrong, you can check at central.pokechatel.ml

**Comment by brusselopole** [comment]
Well, I just checked and no-team-gym was at 0 witch seems in accordance with the gym page

**Comment by Zegorax** [comment]
Ow ? I still have 33 gyms to take
![taken_gyms](https://cloud.githubusercontent.com/assets/20574959/18056427/1f0cddc6-6e0c-11e6-9773-ba8b939bdeda.png)
EDIT: In the bottom, it says 0, but in the main section at the top, it says 33

**Comment by brusselopole** [comment]
The main section count the total gym available to fight for in your area 
The bottom section give you more details about the repartition. 

( maybe we should adjust the translation from "à prendre" to "pour se battre" ? )

**Comment by Zegorax** [comment]
Yes, just made the calculation so yes, I'll rename that in the translations. I thought it was the free gyms because it has the white arena icon, which means in the other parts of the website free gyms not taken. Maybe add a tri-color icon too ? (Like it's blue/red/yellow ?)

**Comment by brusselopole** [comment]
/back-dev give the mic to the pixel-pusher

**Comment by Zegorax** [comment]
/waiting for an awesome project to be even more awesome

**Comment by Zegorax** [comment]
Wontfix ?

**Comment by brusselopole** [comment]
Nope, the first row is dedicated to "global" variables, while the gyms breakdown at the bottom is clearly a division :) Both rows are divided and clearly separated, as for their content.

Feel free to modify on your instance if you feel you need more clarity, but won't be changed for the global.

**Comment by Zegorax** [comment]
Okay, I'll do it by myself ;)
