### ISSUE TITLE
Nest Migration Countdown

### ISSUE THREAD

**Issue by titanicboyke** [brusselopole/Worldopole#232]
I came when surfing on the internet against a website with a countdown to the next migration, now I thought maybe this would be a nice idea to add to worldopole?

![migration](https://cloud.githubusercontent.com/assets/22316434/24718898/067963fa-1a38-11e7-8ad9-0c8aa722360c.png)

http://nestmigration.com/

**Comment by tobias86aa** [comment]
Yes that sure should be something nice :)

**Comment by Obihoernchen** [comment]
Merged #260
