### ISSUE TITLE
Will this also work with the pogom.db ? [more like a question]

### ISSUE THREAD

**Issue by NHGRisk** [brusselopole/Worldopole#24]
hey, I am feeding info to a vserver running mysql into a database called "Map", can i also use this data to feed worldopole with data ? and is there a way to show a spawnmap (like pogom or PokemonGo-Map do in their standalone) ?
thanks! :)

**Comment by brusselopole** [comment]
Hi! 

For your title : No app works only with MySQL server. 
For your bodytext : Yes you can feed this app with ur datas (it's even it's purpose) and there's a spawnmap for each Pokémon. 

You're welcome!
