### ISSUE TITLE
Pokestops

### ISSUE THREAD

**Issue by titanicboyke** [brusselopole/Worldopole#241]
is it possible to make a selection for the pokestop page?
**'all pokestops'** and **'only lured pokestops'**?

in the (variables.json)  is with me "only_lured_pokestops"  :	true"
but there are not always lured pokestops and then I see nothing!
![empty](https://cloud.githubusercontent.com/assets/22316434/24831688/ed372d3c-1c9e-11e7-9c4e-4c90d5afd61d.jpg)

can a solution be found?
I've tried it, but it is a total fiasco

**Comment by Obihoernchen** [comment]
Satisfied with #274?

**Comment by titanicboyke** [comment]
YES :smiley:
