### ISSUE TITLE
Add rarity calculation to cron

### ISSUE THREAD

**Issue by pki0** [brusselopole/Worldopole#256]
My own and user experience in Discord shows that the rarity calculation is freezing the database if pokemon_table is too big.
If the time limit of 24 hours is reached the data.loader is calling the function not once, it's calling the function infinity times! I had 278 processes with rarity calculation in my processlist.

So we should move the rarity calculation to the cron-job with same delay or set the delay to 7 days.

That could solve the error that the query is called multiple times:

All 15 minutes -> crontabs.include.php -> is rarityfile newer then 24 hours? -> call

**Comment by Obihoernchen** [comment]
yep I have the same problem.

We have to take a look at nests cron as well. It should be updated only once a day max (not every 15min).

**Comment by SiteEffect** [comment]
Same problem and really important. I get even PM'd about it by various Worldopole maintainers which are not directly into this GitHub repo. It get's called by every user visiting a front-end page before the first query isn't done - leading to a DB lock.
I like the 15min check, enabling simple include via crontabs.include.php - however, we should make sure that it does not get run multiple times when the loading takes longer than 15 minutes. The same strategy can be used for nests.cron.php.

**Comment by pki0** [comment]
So if we want to stay at cron I would do the following:

Stay at 15 minute cron:

All 15 minutes
- Calculate data points for Dashboard
- Count Pokemon spawns for Pokedex
- <s>Store lat, lon for all Pokemon</s>

Add 24  hour delay into the cron and
- Calculate nests
- Count pokedex total spawns on top of the page
- Calculate rarity
- Calculate spawnrate

This adds 3 new things into the cronjob.

## Why?
- Spawnrate calculation is very hard for ultra common pokemon and delays website
- Pokedex total spawns estimate at a high number is really wrong
- Calculate Rarity as it is but only call the query once

**Comment by SiteEffect** [comment]
Referred to #257

**Comment by Obihoernchen** [comment]
Still TODO:
- [x] improve cron scheduling so nests and rarity doesn't run at the same time?
- [x] count Pokemon spawns for Pokedex + total spawns + spawnrate + spawn diagram and create json
- [x] top50 table for rare pokemon only
- [x] fix initial nests.stats.json creation

**Comment by Obihoernchen** [comment]
See #265
