### ISSUE TITLE
All Strings dissapeared

### ISSUE THREAD

**Issue by CHessDIF** [brusselopole/Worldopole#26]
Hey, at my site:
www.dapole.zockfreunde.de

All Strings are missing :|
Apache Error log tells me:
`[Mon Aug 29 19:37:16.047158 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/core/inc/meta.inc.php on line 36, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.047331 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/core/inc/meta.inc.php on line 42, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.047379 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/core/inc/meta.inc.php on line 46, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.047438 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/index.php on line 62, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.047559 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/index.php on line 65, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.047627 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 5, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049055 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 17, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049089 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 22, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049115 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 22, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049138 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 28, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049162 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 28, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.049196 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 33, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050177 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 43, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050484 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 67, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050519 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 75, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050544 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 75, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050570 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 75, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050595 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/pages/home.page.php on line 75, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050623 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/index.php on line 129, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050648 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/index.php on line 130, referer: http://www.dapole.zockfreunde.de/pokestops
[Mon Aug 29 19:37:16.050675 2016] [:error] [pid 6099] [client 109.90.208.28:48125] PHP Notice:  Undefined property: stdClass::$1 in /var/www/dapole/index.php on line 131, referer: http://www.dapole.zockfreunde.de/pokestops
`

**Comment by brusselopole** [comment]
Hi, 

this was due to a bugged commit for language management. 
Please update to the latest version to fix it. 

Sorry

**Comment by CHessDIF** [comment]
Thank you for the quick answer!
Keep up the brilliant work!  I'll keep you updated when Dapole (For Darmstadt in Germany) will fire up! :)
