### ISSUE TITLE
Pokemon search at Pokedex: Searching only in "seen XX" string

### ISSUE THREAD

**Issue by CHessDIF** [brusselopole/Worldopole#28]
If entering a search String in the search field at the Pokédex,
it only will search in all "seen XX" strings below the pictures.

Examples:
- Entering "Ch" (for Charmander e.g.) won't yield any results.
- Searching for "3" will return all Pokémon seen 3, 30, 13, 53... times.
- Searching for "seen" will return all Pokémon.

**Comment by brusselopole** [comment]
Have you a link, since when the problem is happening ?

**Comment by CHessDIF** [comment]
I will update the site to  commit 0d785e7, and recheck if the error is still ocurring. 
If this ever worked I can't tell when it broke - using the site since today. Sorry.

**Comment by CHessDIF** [comment]
Fixed by using version based on commit 0d785e7.
Thanks.
