### ISSUE TITLE
internal error 500 php Restricted access aru.php and etc

### ISSUE THREAD

**Issue by mimikq** [brusselopole/Worldopole#282]
## Expected Behavior
after clean install today, i received a lot of apache error and php errors on log

## Current Behavior
on home page i can't see mythic spawns : due :  PHP Fatal error:  Call to a member function fetch_object() on boolean in /home/mimik/Worldopole/core/process/aru.php on line 172, referer: http://url

Worldopole/pokemon/4 : is not working too due php issue  : 500 Internal Server Error

Connection:close
Content-Length:0
Content-Typetext/html; charset=UTF-8
DateTue, 02 May 2017 11:56:12 GMT
ServerApache/2.4.10 (Debian)

## Possible Solution
not sure now what to do :( , it looks like some apache2 config or .htaccess file .

## Steps to Reproduce (for bugs)
1.git clone
2.edited install.sh
3. after install, cp -v htaccess .htaccess , edited crontab. 
4.page is up and running but few things are not running 

PHP Warning:  filemtime(): stat failed for /home/mimik/Worldopole/core/js/pokedex.content.js in /home/mimik/Worldopole/functions.php on line 94, referer: http://URL

 PHP Fatal error:  Call to a member function fetch_object() on boolean in /home/mimik/Worldopole/core/process/data.loader.php on line 203, referer: http://URL

PHP Fatal error:  Call to a member function fetch_object() on boolean in /home/mimik/Worldopole/core/process/aru.php on line 172, referer: http://URL 

PHP Warning:  array_reverse() expects parameter 1 to be array, null given in /home/mimik/Worldopole/pages/home.page.php on line 177, referer: http://URL

## Context
Hi all , till today i was running on older version, today i made clean install of the news version from git

## Your Environment

* Version used:today i made fresh git clone, debian 8.7, php5                           5.6.30, apache2                        2.4.10
* URL: 
* Operating System and version (desktop or mobile):

**Comment by pki0** [comment]
Hi, do you use your old variables.json or the new one? (Editied variables.example.json and renamed to variables.json after install)

**Comment by mimikq** [comment]
@pokemonkiel good question, i know that i didn't copied yet, but i can try to rename example ... and test it, from my point me not sure if it is some apache settings or htaccess.

**Comment by pki0** [comment]
@mimikq Okay. For me this looks like an error with your timezone in variables.json. But I'm not 100% sure

**Comment by mimikq** [comment]
@pokemonkiel so it doesn't help too, i used variablas.example.json , same error :(

**Comment by mimikq** [comment]
SOLUTION :  run in Worldopole directory : git checkout d7936cb
