### ISSUE TITLE
Document variables.json

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#285]
Add documentation about variables.json to the wiki.
If anybody feels like it go for it pls!

**Comment by mimikq** [comment]
in case i can help somehow. but me new also in git i know only git clone and pull :) but me learning fast,  i was using WOP long time till shadow ban come.

**Comment by Obihoernchen** [comment]
@mimikq you should be able to create a new wiki page with the github web frontend

**Comment by mimikq** [comment]
@Obihoernchen thx i see, WIP :) there are few system settings which i don't understand but later someone can edit , and add more info or corrections :)

**Comment by mimikq** [comment]
me not sure only about 


recents_filter default > true
recents_filter_rating default > 8
recents_filter_rarity default > 0.01


rest what i know and i found here i put there, in case pls my Eng. is not so good, or for more ideas mistypes please feel free to edit it :)

**Comment by Obihoernchen** [comment]
Thank you @mimikq !!! 
Will add missing information once I have some time.
