### ISSUE TITLE
No Pokemon in the Counter "X Pokemon in $City"

### ISSUE THREAD

**Issue by stylefabrik** [brusselopole/Worldopole#29]
## Expected Behavior

Show Pokemon on Website
## Current Behavior

Website says "0 Pokemon in $City right now", 
but is showing Gyms, Pokestops and recent Spawns
## Possible Solution

Please tell me, i have no clue :dancers: 
## Steps to Reproduce (for bugs)
1. Have PokemonGo-Map running since weeks
2. Cloned the repo local, done all steps in readme
3. Page loads fine, but no pokemon in the counter
## Your Environment
- OS X Server
- Apache2
- mod_rewrite active
- PHP 5+ installed

**Comment by brusselopole** [comment]
Can you provide (as asked) an URL ? We can't help without it, especially since it seems linked to your environment as the website is now deployed and working on several locations :)

**Comment by stylefabrik** [comment]
http://93.215.205.214/worldopole/

**Comment by AL-dot-debug** [comment]
Hi, 

you probably just need to change in variables.json your timezone setting as Neumarkt is GMT+2 not +1  :-)

**Comment by stylefabrik** [comment]
I'm such an Idiot.  Thanks, that fixed it.
