### ISSUE TITLE
map url in raids is hardcoded

### ISSUE THREAD

**Issue by friscoMad** [brusselopole/Worldopole#297]
## Expected Behavior
Clicking in a gym name in raids will lead to RM at the location

## Current Behavior
It goes to /map?coords but there is no way to configure map part

## Possible Solution
We could add another option to variables or somehow identify the map link in menu to take it from that.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Latest version
* URL: http://pokemad.es
* Operating System and version (desktop or mobile): Centos 7

**Comment by michikrug** [comment]
Since stock RM doesn't even support the coordinates URL parameters, should we link to Google maps by default?

**Comment by friscoMad** [comment]
RM support URL coordinates, you just need to disable start map location on
me (or fix RM to skip that option when a location is provided)

2017-07-09 12:18 GMT+02:00 Michael Krug <notifications@github.com>:

**Comment by friscoMad** [comment]
Umm this should be open, it wasn't fixed.

**Comment by Obihoernchen** [comment]
shitty github closed it automatically sry...
