### ISSUE TITLE
Fatal error: Call to a member function fetch_object() on boolean in /*/Worldopole/core/process/data.loader.php on line 500

### ISSUE THREAD

**Issue by edgarborja** [brusselopole/Worldopole#3]
After completing the installation steps, and enabling short tags, I receive this error on http://myserver/Worldopole/index.php

Fatal error: Call to a member function fetch_object() on boolean in /var/www/html/Worldopole/core/process/data.loader.php on line 500

Tried it with PHP7, downgraded to PHP5.6, issue remains the same.

**Comment by brusselopole** [comment]
Should be solved with the latest files (missing php tag) :)

**Comment by edgarborja** [comment]
I followed the error, it was caused by an invalid DB query on line ~494.

This is the MySQL error:
/\* SQL Error (3065): Expression #1 of ORDER BY clause is not in SELECT list, references column 'pogom.pokemon.disappear_time' which is not in SELECT list; this is incompatible with DISTINCT */

Query should be: "SELECT DISTINCT pokemon_id, disappear_time FROM pokemon ORDER BY disappear_time DESC LIMIT 0,12"

MySQL version is 5.7.13-0ubuntu0.16.04.2

**Comment by brusselopole** [comment]
Sorry the issue was too quickly closed ... 
Thanks, it's patched!

**Comment by edgarborja** [comment]
Thanks to you!

It's up and running now :)
