### ISSUE TITLE
Blank page on Ubuntu 16.10 VPS

### ISSUE THREAD

**Issue by Yutsa** [brusselopole/Worldopole#35]
## Expected Behavior

The page should be displayed
## Current Behavior

The page is blank.
## Context

I'm trying to host the site on my Ubuntu 16.10 VPS. But when I enable mod_php the page stays blank. When I disable mod_php it works (with the php parts not working of course).

I tested on my Debian Jessie stable on my local computer and I managed to make it work there.

I tried both php7.0 and php5.6 on the Ubuntu server. 

On my local Debian computer I have php5.6 and it works
## Your Environment

- Version used: 2fb229253e61534b266c4b7210b6b023987b3b0e
- URL: IP of my VPS for now, prefer not to make it public.
- Operating System and version (desktop or mobile): Ubuntu 16.10

**Comment by ItsCEED** [comment]
Did you check your error log?

Also, are you sure you have right setup cuz if the site cant connect to database will show blank page.

**Comment by Yutsa** [comment]
Oh wow sorry I'm dumb I didn't even think to see the log....

`PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/Worldopole/core/process/aru.php:43\nStack trace:\n#0 {main}\n  thrown in /var/www/Worldopole/core/process/aru.php on line 43, referer: http://ip_of_my_vps/`

I didn't have mysqli installed sorry for that !
