### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by ArgusDrise** [brusselopole/Worldopole#352]
I just installed worldopole on my server

then went to my url

und i just see a screen with
 /index
last modified and so on

what is the common location to install it?
is it /domain/
or /domain/worldopole

thx for help

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* URL:
* Operating System and version (desktop or mobile):

**Comment by 123FLO321** [comment]
Did you follow the [Wiki](https://github.com/brusselopole/Worldopole/wiki/Installation-instructions)?
Looks like you did not install/enable php.

**Comment by ArgusDrise** [comment]
i did and php is working

but i think i have to place the path folder different

**Comment by ArgusDrise** [comment]
Got it working 

Closing this 

Thx for help
