### ISSUE TITLE
Live map of the pokedex, failing

### ISSUE THREAD

**Issue by Greenwardog** [brusselopole/Worldopole#359]
## Expected Behavior

for some reason the live map and the heatmap are mixed.  This should be separate, as usual.

## Current Behavior

The information is mixed in the two maps. both the heat and the live.

## Steps to Reproduce (for bugs)

1. enter pokedex and after that into any pokemon. go to the map live.

## Context
![image](https://user-images.githubusercontent.com/20928053/36235352-f33b5ff2-11e7-11e8-81a9-dcf38b29148f.png)

## Your Environment

* Version used: all updated to the last pull and tested in several worldpole
* Operating System and version (desktop or mobile): wrong in mobile as in computer

**Comment by 123FLO321** [comment]
This likely is a problem with Googles new API (Version 3.31) released on 13.02.2018 since nothing is changed in the code for 3 months.

**Comment by Greenwardog** [comment]
this update solves the problem. Thank you very much.
