### ISSUE TITLE
URL rewrite not workin

### ISSUE THREAD

**Issue by Yutsa** [brusselopole/Worldopole#36]
## Expected Behavior

When clicking on a link like "All Pokemon" the /pokemon page should display something.
## Current Behavior

The pages like /pokemon are 404 not found.
## Steps to Reproduce (for bugs)

1. Go to the main page
2. Click on All Pokemon or any other link
## Context

When I'm trying to go to the "All pokemon" page or "Gym" page I get a `404`. However when I look into the `.htaccess` file and enter the real adress like `index.php?page=gym`, it works.

I have mod_rewrite enable, I checked with `sudo a2enmod rewrite` and the `.htaccess` is the original.

The directory with Worldopole is `/var/www/Worldopole` and my apache2 site conf file is : 

``` conf
<VirtualHost *:80>

             ServerAdmin webmaster@localhost
             DocumentRoot /var/www/Worldopole


             ErrorLog ${APACHE_LOG_DIR}/error.log
             CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
## Your Environment

- Version used: 2fb229253e61534b266c4b7210b6b023987b3b0e
- My VPS adresse
- Operating System and version (desktop or mobile): Ubuntu 16.10

**Comment by ItsCEED** [comment]
did you restart the apache? also

`<Directory /var/www/html>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
  </Directory>`

add this, and restart the apache again, also do you have permission set to folders and add . in front of htaccess?

**Comment by Yutsa** [comment]
It works with the `Directory` directive added !

Why did it need that to work ? why is the DocumentRoot inside the VirtualHost not enough ?

**Comment by ItsCEED** [comment]
I have no other explanation than, apache is fucked up.

**Comment by Yutsa** [comment]
Aha thanks anyways ! And do you know if there's a simple way to make the site use the French translations ?

**Comment by ItsCEED** [comment]
Functions

Line 13, change EN to FR

**Comment by ItsCEED** [comment]
Or set languages to false exepct FR to true in variables.json

**Comment by Yutsa** [comment]
Yep the change in the function worked. It didn't change on my browser but on another browser it works. So I guess it's a cache problem or something. Thank you !

**Comment by NHGRisk** [comment]
hey guys, i have the same problem, but when i add `<Directory /var/www/html> Options Indexes FollowSymLinks MultiViews AllowOverride All Order allow,deny allow from all </Directory>` to my apache2 conf in /sites-available and `service restart apache2` i get this error:

> Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.

when i check for the service then via `systemctl status apache2.service` i get this:

> ● apache2.service - LSB: Apache2 web server
>    Loaded: loaded (/etc/init.d/apache2)
>    Active: **failed** (Result: exit-code) since Sun 2016-09-04 08:32:53 EDT; 11s ago
>   Process: 18622 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
>   Process: 17413 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
>   Process: 18649 ExecStart=/etc/init.d/apache2 start **(code=exited, status=1/FAILURE)**
> Sep 04 08:32:53 PokeOrschel systemd[1]: Starting LSB: Apache2 web server...
> Sep 04 08:32:53 PokeOrschel apache2[18649]: Starting web server: apache2 failed!
> Sep 04 08:32:53 PokeOrschel apache2[18649]: The apache2 configtest failed. ... (warning).
> Sep 04 08:32:53 PokeOrschel apache2[18649]: Output of config test was:
> Sep 04 08:32:53 PokeOrschel apache2[18649]: apache2: Syntax error on line 219 of /etc/apache2/apache2.c...sed.
> Sep 04 08:32:53 PokeOrschel apache2[18649]: Action 'configtest' failed.
> Sep 04 08:32:53 PokeOrschel apache2[18649]: The Apache error log may have more information.
> Sep 04 08:32:53 PokeOrschel systemd[1]: _apache2.service: control process exited, code=exited status=1_
> Sep 04 08:32:53 PokeOrschel systemd[1]: **Failed to start LSB: Apache2 web server.**
> Sep 04 08:32:53 PokeOrschel systemd[1]: _Unit apache2.service entered failed state._
> Hint: Some lines were ellipsized, use -l to show in full.

![unbenannt](https://cloud.githubusercontent.com/assets/21179315/18231052/c57b98c8-72ad-11e6-932d-31bc24d84337.PNG)
