### ISSUE TITLE
Timezones and Interval not working properly

### ISSUE THREAD

**Issue by ghost** [brusselopole/Worldopole#37]
I followed the instructions and everything is working fine except for the time information.
I'm located on the US East Coast (EST: GMT-4) and I have to choose between getting the correct "last seen" information, or the correct graph.

If I set the variables.json "time_interval" to -4, then the last seen time, and the "current pokemon" is not working properly.
If I set the variables.json "time_interval" to 0, then the last seen time works, but the graph on the pokemon page is offset by 4 hours.
## Expected Behavior

I would expect that setting the time interval and timezone would work, but it is not working correctly.
## Current Behavior

Either the last seen or the graph is "offset" by the +/- number provided.
## Possible Solution

Properly use the time interval and timezone settings, or simply ask for the information once.
I think the problem may be due to the information being both in the config.php and variable.json that it may be counted twice in some situations.
Maybe I'm not using the "timezone" in the json correctly. I have it set to "New_York/America"
## Steps to Reproduce (for bugs)

Set up the site and check the "last seen" vs the "graph" in the pokemon page.
After 24 hours it may be hard to notice, since you will have data points for all hours, but if you start from scratch, the data is offset.

**Comment by AL-dot-debug** [comment]
Duplicate issue https://github.com/brusselopole/Worldopole/issues/30

**Comment by ghost** [comment]
Not exactly the same problem, but I guess the source of the problem is the same. I'll check the DB config. Thanks for the quick response.

**Comment by AL-dot-debug** [comment]
Timezone is a mess, we need to manage them better and it will solve both problems ( I hope at least ;) )
