### ISSUE TITLE
Translation not showing up

### ISSUE THREAD

**Issue by stylefabrik** [brusselopole/Worldopole#38]
## Expected Behavior

See German Translations on the Website.
## Current Behavior

Translated Words are just blank/hidden/not showing on the Page.
## Steps to Reproduce (for bugs)
1. I edited translations.json, added lines with "DE" 
2. Edited my variables.json, DE:true - all other languages false
## Your Environment
- Version used: latest
- URL: http://pkm923.chickenkiller.com/worldopole/
- Operating System and version (desktop or mobile): OS X Server

**Comment by brusselopole** [comment]
You must keep "en" : true IN variables.json FILE. You can add or remove others languages following other existing language example.

**Comment by stylefabrik** [comment]
I changed the value of "en" to true again, but the translation is still not showing up.

**Comment by ItsCEED** [comment]
You are doing it wrong, dont post an issue if you are not sure what you are doing.

edit Functions
Line 13, change EN to DE

Also read other issues before posting/asking something, this is answered in #36

**Comment by stylefabrik** [comment]
Maybe the hint with Line 13 should be added to the readme. Thanks!
