### ISSUE TITLE
Bad formated time_interval

### ISSUE THREAD

**Issue by krummrey** [brusselopole/Worldopole#39]
I'm Trying to get it to work on my Mac, but I get this response:

> Bad formated time_interval in variables.json. Please use +X or -X format only (eg for Brussels : +2) without leading or ending space.

I didn't change it, it still is:
         "time_inverval"    : "+2",

Am I missing a step?

**Comment by brusselopole** [comment]
Might be related to #30 so we're digging into it but might take time
