### ISSUE TITLE
Need Help to install the website. I get weird results at the moment :/

### ISSUE THREAD

**Issue by Demokdawa** [brusselopole/Worldopole#41]
Hello, I'm really in trouble about the installation of the website. I got weird result.
  -I don't have acces to pokemon/pokestops/gym/etc pages.
  -I only have acces to the first index page, but it's so weird and buggy ..

I obviously missed something. 

Thanks in advance for your help !

![image](https://cloud.githubusercontent.com/assets/21694921/18184723/b416117c-709a-11e6-8cf8-a52d518d78fa.png)

**Comment by ItsCEED** [comment]
Read the last 3 closed issues. And my first pull request :) this is not support forum this is issue to report/request things.

**Comment by Demokdawa** [comment]
I know, but this is the only place to talk about install problems xD

I have read your tutorial post and don't know how i can get this to work xD

**Comment by ItsCEED** [comment]
There you go specialy for you, read the README now :) and feel free to close the issue :)

**Comment by 56k-amaury** [comment]
Need a Windows install guide.
