### ISSUE TITLE
Potential arbitrary file inclusion.

### ISSUE THREAD

**Issue by qkaiser** [brusselopole/Worldopole#5]
Hi there !

The way you include files in index.php (https://github.com/brusselopole/Worldopole/blob/master/index.php#L95) could be abused to include arbitrary files if the server is running an outdated version of PHP (<5.3 if I'm not mistaken).

Reference: http://php.net/manual/en/security.filesystem.nullbytes.php

Cheers,
Q

**Comment by brusselopole** [comment]
Hi! 
thanks for the advice! 

We added a double check on page inclusion to be sure the page requested is only on the website directory.

**Comment by brusselopole** [comment]
Radical way, Fixed! ;)
