### ISSUE TITLE
*dot* missing at Pokemon counter on main page

### ISSUE THREAD

**Issue by NHGRisk** [brusselopole/Worldopole#58]
## Expected Behavior

It should say "X Pokémon in Y right now."
## Current Behavior

It acutally says "X Pokémon in Y right now" (so the dot at the end is missing)
## Possible Solution

I made and ugly fix adding a " . " in line 17 in home.page.php 
`<?= sprintf($locales->WIDGET_POKEMON_SUB->$lang, $config->infos->city); ?></a>.</p>`
## Steps to Reproduce (for bugs)

1. visit http://brusselopole.be/ for example at see for yourself
## Your Environment

- Version used:
- URL:
- Operating System and version (desktop or mobile):

**Comment by Obihoernchen** [comment]
Actually it's no sentence so I removed all dots.
Looks better I think ;)

85ef960f9e35fde498312509f0d5b18d84e97b05
