### ISSUE TITLE
replace short tags (<?) with full open tag (<?php) 

### ISSUE THREAD

**Issue by sorokyl** [brusselopole/Worldopole#6]
I encountered this issue when setting up the app.  by default, short_open_tag are disabled in php.ini.  I enabled this to get it to work.  

The behavior I was experiencing was raw php code displayed on the screen, some of the site was working some wasn't. 

Thanks!

**Comment by brusselopole** [comment]
We're working on to find/replace all missing tags! 
If u found some, to not hesitate to denounce them!

**Comment by sorokyl** [comment]
core/process/data.loader.php

**Comment by brusselopole** [comment]
Patched :-) 
https://github.com/brusselopole/Worldopole/commit/ac6e45cb0611f0c42948316996908ed362156e44

**Comment by marbink** [comment]
core\js\pokemon.maps.js.php

**Comment by brusselopole** [comment]
Commit https://github.com/brusselopole/Worldopole/commit/c901dee21e1a900d2b51f2f037774ea392540d1d should have fixed all missing tags 

Thanks!
