### ISSUE TITLE
[Feature Request] Gym icons with gym level

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#60]
Like this: https://github.com/PokemonGoMap/PokemonGo-Map/pull/782
## Possible Solution

Add some icons and load based on gym level. Really easy.

**Comment by AL-dot-debug** [comment]
Easy peasy ^^ 

@nithou can you create the icons? :-)

**Comment by nithou** [comment]
Mmmh sorry but on my side it's quite ugly and will just overload even more the maps :/

**Comment by NHGRisk** [comment]
@56k-amaury i could, just tell me the size and file format (prob. .png) needed :)

**Comment by Obihoernchen** [comment]
@nithou so close this?

**Comment by SiteEffect** [comment]
Should be addressed with the latest gym-map overhaul of recent PRs.

**Comment by Obihoernchen** [comment]
Merged to https://github.com/brusselopole/Worldopole/issues/97
