### ISSUE TITLE
No Maps on subpages such as /gym or /pokestops

### ISSUE THREAD

**Issue by NHGRisk** [brusselopole/Worldopole#65]
## Expected Behavior

small maps showing of where gyms are located and their respective team color
same for stops/lured stops
## Current Behavior

everything works fine, except all the small maps are missing and there is a big white space instead
## Possible Solution

no idea at all
## Steps to Reproduce (for bugs)

1. visit https://pokemapoberursel.de/
2. see for yourself
   3.
   4.
## Context

it appeared yesterday on another VPS. i got a new one and set that up and still got the same error
## Your Environment

- Version used: https://github.com/brusselopole/Worldopole/commit/6202ad05c6567d6c0633cc5ca48b56cbb7b257d7
- URL: https://pokemapoberursel.de/
- Operating System and version (desktop or mobile): Debian 8

**Comment by ItsCEED** [comment]
https://pokemapmk.xyz/testovi/gym
https://pokemapmk.xyz/testovi/pokestops

Fresh install, its not script side issue.

**Comment by NHGRisk** [comment]
well i did another fresh install and still have the exact same issue, also upgraded all required packages

**Comment by NHGRisk** [comment]
Problem is solved thanks to @56k-amaury 

Explanation:
the paypal donation button format was wrong. i cleaned the code to that with spaces like u usually do

but the site didnt like that too much :D when u remove all the spaces to that:
`{
             "type"         : "html",
             "value"        : "<form action='https://www.paypal.com/cgi-bin/webscr' method='post' target='_top'><input type='hidden' name='cmd' value='_s-xclick'><input type='hidden' name='hosted_button_id' value='GVD7FZCBYGRPA'><input type='image' src='https://www.paypalobjects.com/de_DE/DE/i/btn/btn_donate_SM.gif' border='0' name='submit' style='margin-top:15px' alt='Jetzt einfach, schnell und sicher online bezahlen – mit PayPal.'><img alt='' border='0' src='https://www.paypalobjects.com/de_DE/i/scr/pixel.gif' width='1' height='1'></form>"
         }`
it works!
