### ISSUE TITLE
Having the website for your town? 

### ISSUE THREAD

**Issue by brusselopole** [brusselopole/Worldopole#7]
Drop the link! 
( we'll add them to the Wordlopole page on Brusselopole http://brusselopole.be/worldopole )

**Comment by kiralydavid** [comment]
http://stats.pokemiskolc.tk/

Thanks for the awesome work :)

**Comment by brusselopole** [comment]
Currently live on : 
[Neuchâtel, Switzerland](https://central.pokechatel.ml/)
[Oldenburg, Germany](http://go.oldenburg.io/)
[Miskolc, Hungary](http://stats.pokemiskolc.tk/)

**Comment by aastroza** [comment]
[Santiago, Chile](http://santia-go.cl) :D (work in progress)

**Comment by Atroci** [comment]
poke.cavernah.com (just got it working)

**Comment by urinella** [comment]
http://pokemonkiel.zapto.org/ Kiel, Germany 

with German translation and Livemap

**Comment by Maveryy** [comment]
http://pokenatal.com.br/ :D
Natal (Brasil)

**Comment by 56k-amaury** [comment]
@Maveryy You're at GMT -3, not -4 :-)

**Comment by Maveryy** [comment]
@56k-amaury I know but when I use -3, the "When was it last seen?" section on any Pokemon page was "1 hour ago" so I tried to use -4 to fix that (still the same issue)

**Comment by AL-dot-debug** [comment]
@Maveryy come some times on [discord](https://discord.gg/yQ28w) or check the [Wiki page](https://github.com/brusselopole/Worldopole/wiki/Pokemon-count-on-home-page-is-set-at-0-or-1000) about your bug

**Comment by krummrey** [comment]
[Ahrensburg in Germany](http://pokestorm.info.tm)

**Comment by deivuh** [comment]
[Guatemala City, Guatemala](http://pogodexgt.xyz) Live, but still working on it :)

**Comment by WojtekK78** [comment]
[Warsaw Poland](http://warszawa.pokemonfun.pl) - working still some polishing to do :)

**Comment by z0n** [comment]
[Aachen, Germany](https://128bit.org/worldopole/)

**Comment by fusenuk** [comment]
For my University campus (Canterbury, England) - http://anewpla.net/poke/ 

http://anewpla.net/poke/live - added a live map of pokemon

**Comment by Obihoernchen** [comment]
Berlin, Germany: https://obihoernchen.net/pokemon/

**Comment by drallieiv** [comment]
Lyon France, but not really public yet. Have to work out a few server issues

**Comment by mimikq** [comment]
Bratislava Slovakia, we are live but after shadowban only for payed user.

**Comment by billyjbryant** [comment]
[Louisville, KY, US](https://louisvillepgo.life/)  Live for the public!

**Comment by pgmap** [comment]
http://lodz.pgmap.pl
Poland, Łódź

And Alll from :  http://brusselopole.be/worldopole wasn't working anymore

Cheers

**Comment by Obihoernchen** [comment]
Hi,
sorry this isn't updated anymore.
