### ISSUE TITLE
Last seen: Days/Day wrong display in pokemon.page.php

### ISSUE THREAD

**Issue by urinella** [brusselopole/Worldopole#72]
## Expected Behavior

When was it last seen?  1 day or 2 days ...
## Current Behavior

When was it last seen? 1 day 2day ....
## Possible Solution

functions.php: line 80

 if ( $difference_value <= 1 ) { 

better:  if ( $difference_value < 1 ) {

But this does not solve the day display, only solves correct week display.

I have no idea what so change. The calculation in functions.php seems correct.

When I look on other Worldopole pages from other users, some have a problem here, some not.

This is a reminder from my message in discord with @Obihoernchen

**Comment by Obihoernchen** [comment]
@urinella Can you please test my PR? For me this works perfectly fine for everything.

**Comment by urinella** [comment]
@Obihoernchen Thanks

Edit: My mistake. This fixed the problem
