### ISSUE TITLE
Translation file doesn't have POKEMON_CANDIES entry so causes errors on pokemon page

### ISSUE THREAD

**Issue by fusenuk** [brusselopole/Worldopole#77]
This file - https://github.com/brusselopole/Worldopole/blob/master/core/json/translations.json

does not have an entry for 'POKEMON_CANDIES' which is then attempted to be read on line 128 of this file - https://github.com/brusselopole/Worldopole/blob/master/pages/pokemon.page.php
## Current Behavior

The error_log file on the webserver shows an exception error
## Possible Solution

Add in the 'POKEMON_CANDIES' entry into the translation file
## Steps to Reproduce (for bugs)

load the an individual pokemon's info page e.g. blah.com/pokemon/10 and then see that it says 

Next Evolution Requirements :   12 Caterpie

without the word candy on the end.

**Comment by Obihoernchen** [comment]
thx will fix!
