### ISSUE TITLE
Main page not working 

### ISSUE THREAD

**Issue by dero2k** [brusselopole/Worldopole#8]
Hi
I set up the page for my city. 
On the front page it shows 0 Pokémon and 0 gyms. 
But if I go to the gym page or Pokémon page everything works.

**Comment by brusselopole** [comment]
Could you give us your URL?

**Comment by mfaalk** [comment]
Same here, http://lken.nu

**Comment by brusselopole** [comment]
@mfaalk release https://github.com/brusselopole/Worldopole/commit/4ddb77a06088a561e9189b24a68e5f8c10a41c1e should have fix your problem

**Comment by mfaalk** [comment]
I already have it, didn't solve my problem.

**Comment by brusselopole** [comment]
Well, as much as I can see it seems that the SQL req : `SELECT DISTINCT pokemon_id, disappear_time FROM pokemon ORDER BY disappear_time DESC LIMIT 0,12` does not return results (witch is strange as you have the datas ) Release https://github.com/brusselopole/Worldopole/commit/4ddb77a06088a561e9189b24a68e5f8c10a41c1e is dedicated to this query ... Could you check on your SQL if the req sort results and in your /core/process/data.loader.php line 501 if the $req is the same one?

**Comment by mfaalk** [comment]
Alright, I found it.. 

I just downloaded the zip file to get an updated version. Unfortunately, still the same error. 
I decided to do some testing.
So I tried to echo something in the while loop to count the rows.
I simply wrote

> echo $data->pokemon_id . " - " . $data->disappear_time . "<br>";

and all my rows was displayed in the top left corner with the correct data.
So then I knew the query was working properly.
I opened home.page.php and saw that you open your php tags with just <?
I opened php.ini and set short_open_tag to On.
Then I restarted wamp services and it was all working.
I think you should insert "php_value short_open_tag 1" in htaccess.
