### ISSUE TITLE
Dashboard ?

### ISSUE THREAD

**Issue by dero2k** [brusselopole/Worldopole#9]
Would It be possible to add the dashboard you have on your page to the repo ?

**Comment by brusselopole** [comment]
Hi, 
the dashboard needs CRONTAB, so it's planed for a future release

**Comment by nikos90** [comment]
I am very interested in the dashboard too.

**Comment by ItsCEED** [comment]
@nikos90 we are all unterested :) chill and wait for the next bigger update

**Comment by AL-dot-debug** [comment]
https://github.com/brusselopole/Worldopole/commit/c9899b9e66b4f4c7545b52af9ca91a6aee215ece
