### ISSUE TITLE
Effect "wow" is coded but nowhere implemented

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#93]
## Expected Behavior

Effect "wow", like "pokemon-single" for blue glow, should do something. It is coded for the very most recent Poké on "home.page.php".

## Current Behavior

It's just not there.

## Possible Solution

Implement another hover effect in the css file like "pokemon-single" and add a .png to "img" folder.

## Steps to Reproduce (for bugs)

1. Open homepage
2. Watch recent Pokémon
3. Directly loaded Pokémon are blue glowing on hovering
4. All new added Pokémon while dynamic loading do not show an effect

## Your Environment

* Version used:
* URL:
* Operating System and version (desktop or mobile):

**Comment by SiteEffect** [comment]
Seems like I had a very old version with "wow" coded instead of "pokemon-single" in the "aru.php" file. It's gone now, don't know when exactly so we can close this issue.

**Comment by Obihoernchen** [comment]
Oh yeah now I remember :D I fixed it ~1 month ago hahaha https://github.com/brusselopole/Worldopole/commit/c5bef231f0ba40d1a21fbb053146932a5fa3561c
