### ISSUE TITLE
[Feature Request] Dynamical loading "alltrainer" page

### ISSUE THREAD

**Issue by SiteEffect** [brusselopole/Worldopole#98]
## Expected Behavior

Follow a second button "Full list" instead of "Search" on "trainer" page to obtain a full view of all trainers, without their Pokémon, which loads around 50 trainers dynamically when scrolling further down. This list can be sorted by "name","level" and "gym Pokémon".

## Current Behavior

We just have the top 30 (for some pages top 100) list which is nice for the top player but uninteresting to watch for all the other user.

## Possible Solution

Create a new page "alltrainer.page.php" with less content of detail for the trainer div-pattern. Change data.loader.php or ajax to handle the desired job. Also possible to cache this page every X hours wie cron to take stress from the DB. Quick implementation by copy/paste the trainer page data loader and some deprecations of Pokémon CP, IVs etc. for the DB request.
Implement sort options, clickable by column label, by using multisort and reload list.

name: name->level
level: level->gym Pokémon
gym Pokémon: gymPokémon -> level.

**Comment by SiteEffect** [comment]
^ nice that GitHub shows uncertainties in english grammar - probably all of them wrong.

**Comment by SiteEffect** [comment]
Good approach by https://pokemonkiel.de/spytrainers.php

**Comment by Obihoernchen** [comment]
Let's move discussion to #113
